version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    pull-request-branch-name:
      separator: "-"
    assignees:
      - storezhang
    reviewers:
      - storezhang

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    pull-request-branch-name:
      separator: "-"
    assignees:
      - storezhang
    reviewers:
      - storezhang
